# Generated by Django 6.0.3 on 2026-03-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.CharField(default='2026', max_length=10),
        ),
    ]
