# Generated by Django 6.0.3 on 2026-04-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_schoolyear_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='course',
            field=models.CharField(default='BSIT', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
