# Generated by Django 6.0.3 on 2026-04-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_member_course_member_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='semester',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
