# Generated by Django 6.0.3 on 2026-04-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_member_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='semester',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
