# Generated by Django 6.0.3 on 2026-04-13 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attendance_files/')),
                ('event', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time_type', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2026, 4, 13)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.CharField(default='1st Semester', max_length=50),
            preserve_default=False,
        ),
    ]
