# Generated by Django 6.0.3 on 2026-04-14 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_folder_fileresource_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.folder'),
        ),
    ]
