# Generated by Django 6.0.3 on 2026-04-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_alter_organization_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
