# Generated by Django 6.0.3 on 2026-05-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_organization_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='sidebar_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
