# Generated by Django 6.0.3 on 2026-05-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_officer_sidebar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.organization'),
        ),
    ]
