# Generated by Django 6.0.3 on 2026-05-04 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_attendance_organization_attendancefile_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.organization'),
        ),
    ]
