# Generated by Django 6.0.3 on 2026-05-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_officer_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=20),
        ),
    ]
