# Generated by Django 6.0.3 on 2026-05-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_member_amount_paid_member_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
