# Generated by Django 6.0.3 on 2026-05-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_member_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='department',
        ),
    ]
