# Generated by Django 6.0.3 on 2026-05-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_remove_member_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year_level',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
